// Install generated Codex roles from the canonical Markdown role bodies.
import fs from 'node:fs';
import path from 'node:path';
const [action, skill, home, dry] = process.argv.slice(2);
const marker = '# Generated by delegate-kit; source: agents/dk-*.md';
const stamp = new Date().toISOString().replace(/[:.]/g, '-');
function read(file) { try { return fs.readFileSync(file, 'utf8'); } catch (e) { if (e.code === 'ENOENT') return null; throw e; } }
const changes = [];
for (const name of fs.readdirSync(path.join(skill, 'agents')).filter(n => /^dk-.*\.md$/.test(n))) {
  const source = read(path.join(skill, 'agents', name));
  const match = /^---\n([\s\S]*?)\n---\n([\s\S]*)$/.exec(source);
  if (!match) throw new Error(`Invalid role frontmatter: ${name}`);
  const role = /^name: (.+)$/m.exec(match[1])?.[1];
  const description = /^description: (.+)$/m.exec(match[1])?.[1];
  if (!role || !description) throw new Error(`Missing role metadata: ${name}`);
  const file = path.join(home, 'agents', `${role}.toml`);
  const old = read(file);
  if (old !== null && !old.startsWith(marker)) {
    if (action === 'uninstall') continue;
    throw new Error(`Refusing to replace unmanaged ${file}; move or rename that custom role first`);
  }
  const content = action === 'uninstall' ? null : `${marker}\nname = ${JSON.stringify(role)}\ndescription = ${JSON.stringify(description)}\n${role === 'dk-implementer' ? '' : 'sandbox_mode = "read-only"\n'}developer_instructions = ${JSON.stringify(match[2].trim())}\n`;
  if (old !== content) changes.push({ file, old, content });
}
// Remove only the old managed block; keep every other setting byte-for-byte.
const configFile = path.join(home, 'config.toml');
const oldConfig = read(configFile);
if (oldConfig !== null) {
  const content = oldConfig.replace(/^# >>> delegate-kit agents >>>\r?\n[\s\S]*?^# <<< delegate-kit agents <<<[^\S\r\n]*(?:\r?\n|$)/m, '');
  if (content !== oldConfig) changes.push({ file: configFile, old: oldConfig, content });
}
for (const { file, old, content } of changes) {
  console.log(`${dry === '1' ? 'would ' : ''}${content === null ? 'remove' : 'update'} ${file}`);
  if (dry === '1') { if (content !== null) console.log(content); continue; }
  fs.mkdirSync(path.dirname(file), { recursive: true });
  if (old !== null) fs.copyFileSync(file, `${file}.bak-delegate-kit-${stamp}`);
  if (content === null) fs.unlinkSync(file);
  else { const tmp = `${file}.${process.pid}.tmp`; fs.writeFileSync(tmp, content); fs.renameSync(tmp, file); }
}
